export const HTTP_STATUS_CODE = {
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  HEURISTIC_EXPIRATION: 113,
  MISCELLANEOUS_WARNING: 199,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  TRANSFORMATION_APPLIED: 214,
  IM_USED: 226,
  MISCELLANEOUS_PERSISTENT_WARNING: 299,
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  UNUSED: 306,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
  TOO_MANY_REDIRECTS: 310,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECT_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  UNORDERED_COLLECTION: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUEST: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
};

export const HTTP_METHOD = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
};

export const HEADER_PARAM = {
  CLIENT_MESSAGE_ID: 'clientMessageId',
  TRANSACTION_ID: 'transactionId',
  ACCEPT_LANGUAGE: 'Accept-Language',
  AUTHORIZATION: 'Authorization'
};

export const SYSTEM_FORMAT_DATA = {
  DATE_FORMAT: 'DD/MM/YYYY',
  DATE_TIME_FORMAT: 'DD/MM/YYYY HH:mm:ss',
  MONTH_TIME_FORMAT: 'MM/YYYY',
  DATE_FORMAT_MILLISECONDS: 'YYYYMMDDHHmmssSSS',
  EMAIL_FORMAT: '[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+',
  PHONE_FORMAT: '^[ ]*((\\84)|0)([0-9]{9,10})[ ]*',
  FLOAT_FORMAT: '[^.]*([.](.{1,2}))?',
  NUMBER_FORMAT: '[^.]+',
};

export const STORAGE_NAME = {
  USER_LOGIN: 'USER_LOGIN',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN'
};

export const SERVICE: any = {
  TICKET: 'TICKET_SERVICE',
};

export const ObjectIDManager = {
  REQUEST_LOGIN_TRUE: 1, //  cho phep dang nhap
  AGENT_LOGIN: 2,
  LOGOUT: 3, //  dang xuat
  HAVE_MESSAGE: 4, //
  MESSAGE: 5, //  khi send message
  LEAVE_CONVERSATION: 9, //  roi khoi hoi thoai
  SEND_FILE: 20,
  RECEIVE_FILE: 21,
  USER_JOIN_CONVERSATION: 34,
  CUSTOMER_LOGIN: 37, //  tao moi visitor moi
  UPDATE_VISITOR_INFO: 41, // cap nhat visitor
  AGENT_NOT_RESPONSE_INCOMING_CHAT: 42,
  AGENT_RESPONSE_INCOMING_CHAT: 43,
  AGENT_GET_CONV_HISTORY: 44,
  AGENT_GET_MESSAGE_HISTORY: 45,
  AGENT_END_CONVERSATION: 49,
  AGENT_FRIEND_LIST: 50,
  AGENT_CREATE_CONVERSATION: 51,
  GET_LIST_AGENT: 53,
  TRANSFER_CHAT_TO_AGENT: 54,
  TRANSFER_CHAT_TO_AGENT_RESULT: 55,
  RESPONSE_TRANSFER_CHAT_TO_AGENT: 56,
  FRIEND_LIST_UPDATE: 62,
  CONVERSATION_UPDATE: 63,
  AGENT_LEFT_CONVERSATION: 64,
  AGENT_RESPONSE_INCOMING_CHAT_SUPERVISOR: 67,
  CUSTOMER_END_CONVERSATION: 69,
  AGENT_END_CONVERSATION_CUSTOMER: 71, // agent ket thuc hoi thoai
  SURVEY_SEND_DATA_TO_CUSTOMER: 139,
  SURVEY_UPDATE_RESPONSE_CUSTOMER: 138,
  AGENT_INFO_CUSTOMER: 72, // thong tin agent
  RESPONSE_AGENT_MISS_CHAT_TO_CUSTOMER: 76, //
  AGENT_HAS_CUSTOMER: 77,
  RESPONSE_CUSTOMER_GET_HISTORY_CHAT: 78, //  get history chat
  CUSTOMER_GET_HISTORY_CHAT: 79, //  get history chat
  GET_SERVICE_LIST: 80,          // web client request danh sach service
  RESPONSE_SERVICE_LIST: 81,     // tra ve danh sach service cho web client
  CHAT_SUPER_SPY: 83,
  CHAT_SUPER_SPY_END: 91,
  CUSTOMER_RESUMING_REQUEST: 86, // yeu cau resume lai session
  CUSTOMER_RESUMING_RESPONSE: 87, // response resume session
  NOTIFY_TYPING: 88,
  LIKE: 89,
  DISLIKE: 90,
  CHAT_SUPER_SUPPORT_END: 92,
  TRANSFER_CHAT_RESPONSE: 93,
  SUPPORT_CHAT_RESPONSE: 94,
  CHAT_SUPER_JOIN: 84,
  AGENT_LOGOUT: 95,
  CHAT_SUPER_JOIN_END: 97,
  COMMENT: 98,
  RESPONSE_TRANSFER_CHAT_TO_AGENT_RESULT: 99,
  OFFLINE_MESSAGE_RESPONSE: 100,
  BAN_CUSTOMER: 101,
  AGENT_RESUME_RESPONSE: 102,
  END_INTERNAL_CHAT: 103,
  GET_INTERNAL_HISTORY: 104,
  TRANSFER_CHAT_TIMEOUT: 105,
  WARNING_CUSTOMER_TIMEOUT: 107,
  CUSTOMER_TIMEOUT_CONVERSATION: 108,
  SEND_IS_CHAT_TYPING: 106,
  CUSTOMER_UPDATE_USER_INFO_ERROR : 110,
  HOLD_UNHOLD_CHAT : 111,
  NOTIFY_HOLD_CHAT : 112,
  NOTIFY_HOLD_TIMES : 113,
  NOTIFY_REPLY_FIRST_MSG : 114,
  NOTIFY_REPLY_NEXT_MSG : 115,
  MORE_CHAT_MESSAGE: 130,
  RECEIVE_MESSAGE: 136,
  LEAVE_MESSAGE : 144,
  SHOW_LEAVE_MESSAGE : 145,
  KICK_BECAUSE_SUPER_ROB: 146,
  SUPER_ROB_CHAT: 147,
  SUPER_END_CONVERSATION: 148,
  CHAT_SUPER_JOIN_ERROR_MAX: 149,
  CHAT_SUPER_ROB_ERROR_MAX: 150,
  SEND_PING: 111111,
  SUBSCRIBE_CONVERSATION: 1002,
  UNSUBSCRIBE_CONVERSATION: 1003,
  PUSH_CONVERSATION_TO_AGENT: 1005
}
